org: albertmorales1398
app: swapi-app
service: rimac-test-swapi

provider:
  name: aws
  stage: beta
  region: us-east-1
  runtime: nodejs20.x

plugins:
  - serverless-offline

functions:
  api:
    handler: /src/handler.handler
    events:
      - httpApi: "*"
