org: albertmorales1398
app: swapi-app
service: rimac-test-swapi

provider:
  name: aws
  stage: beta
  region: us-east-1
  runtime: nodejs20.x
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:GetItem
        - dynamodb:Query
      Resource:
        - arn:aws:dynamodb:${self:provider.region}:*:table/HistoryTable

custom:
  environment:
    HISTORY_TABLE: History

plugins:
  - serverless-offline

functions:
  api:
    handler: src/handler.handler
    events:
      - httpApi: "*"


resources:
  Resources:
    HistoryTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: HistoryTable
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
    