org: albertmorales1398
app: swapi-app
service: rimac-test-swapi

provider:
  name: aws
  stage: beta
  region: us-east-1
  runtime: nodejs20.x
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:GetItem
        - dynamodb:Query
      Resource:
        - arn:aws:dynamodb:${self:provider.region}:*:table/HistoryTable
        - arn:aws:dynamodb:${self:provider.region}:*:table/CacheTable
        - arn:aws:dynamodb:${self:provider.region}:*:table/CustomDataTable

custom:
  environment:
    HISTORY_TABLE: HistoryTable
    CACHE_TABLE: CacheTable
    CUSTOM_DATA_TABLE: CustomDataTable

plugins:
  - serverless-offline

functions:
  api:
    handler: src/handler.handler
    timeout: 10
    memorySize: 256
    events:
      - httpApi: "*"


resources:
  Resources:
    HistoryTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: HistoryTable
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
          - AttributeName: createdAt
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
          - AttributeName: createdAt
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST
    CacheTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: CacheTable
        AttributeDefinitions:
          - AttributeName: cacheKey
            AttributeType: S
        KeySchema:
          - AttributeName: cacheKey
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
    CustomDataTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: CustomDataTable
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST